
// this file is automatically generated:
// please edit 'context.yaml', and then:
// run the doit command `python dodo.py generate` or `doit generate`.

#error "This file is automatically generated; please run `python dodo.py source` or `doit source` from command line"
