// this file is automatically generated:
// please edit 'context.yaml', and then:
// run the makefile `make source`.

#error "This file should be automatically generated; please run `make source` from command line"
