M48
; DRILL file {KiCad (6.0.7)} date Tue Jan 17 09:43:17 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-17T09:43:17-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
%
G90
G05
T1
X4.3496Y-2.7124
X4.3496Y-2.7574
X4.3531Y-2.8724
X4.3581Y-2.9124
X4.4181Y-2.9324
T0
M30
