M48
; DRILL file {KiCad (6.0.7)} date Tue Jan 17 09:38:22 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-17T09:38:22-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X4.2974Y-2.4667
X4.2974Y-2.6081
X4.4388Y-2.4667
X4.4388Y-2.6081
T0
M30
